[phases.setup]
nixPkgs = ["nodejs", "cacert", "nss", "nspr", "atk", "cups", "dbus", "expat", "libdrm", "libxkbcommon", "mesa", "pango", "alsa-lib", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxcb", "xorg.libXcursor", "xorg.libXi", "xorg.libXrender", "xorg.libXtst"]

[phases.build]
cmds = ["npm install"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"